Add option to control element collision
Patrick2562/mtasa-pAttach pull request #15
Opened 2024-07-15 04:28 UTC by CrosRoad95

2024-07-30 17:03 UTC, CrosRoad95 commented
@Patrick2562 review

2024-08-04 17:06 UTC, Patrick2562 commented
It would be nice to make it more universal and be able to switch more things on and off. _(interior/dimension change, ...)_
The function could be `setConfigOption(name, value)` / `getConfigOption(name)`.

2024-08-19 13:18 UTC, CrosRoad95 commented
Update, please review.

2024-08-19 22:55 UTC, Fernando-A-Rocha requested changes

2024-08-19 22:55 UTC, Fernando-A-Rocha commented on client.lua
> +        self.options[name] = value
Add assert for name and value parameters

2024-09-01 06:16 UTC, CrosRoad95 commented
Are those two asserts i added good enough?

2024-09-11 13:55 UTC, CrosRoad95 commented
@Fernando-A-Rocha

2024-09-11 22:43 UTC, Fernando-A-Rocha approved these changes
Yes all good Crossy 👌🏼

2024-09-16 19:32 UTC, CrosRoad95 commented
So when it get merged? @Patrick2562

2024-09-17 14:21 UTC, Patrick2562 commented
next week, i don't have time to check it in-game and I would like to make some changes before the next release

2024-09-17 14:21 UTC, Patrick2562 commented
> So when it get merged? @Patrick2562

next week, i don't have time to check it in-game and I would like to make some changes before the next release

2024-09-28 18:07 UTC, merged